# 自撸 TDEngine 镜像，抵制各种行为的技术抑制！
# 来自某位暂未跻身福布斯排行榜的软件工程师。
# 本镜像使用 Debian 操作系统，据说这是最最最专业的操作系统。
# 
# *****************************************************************************
# **  注意：（国内网络各种复杂情况，懂得都懂。）                            ***
# **  所以，非必要不采用apt-get install方式安装，而是先从官网下载软件包。   ***
# **  官方软件包地址：https://www.debian.org/distrib/packages               ***
# *****************************************************************************
#
# 制作镜像过程中，如果遇到失败、报错等，不要着急，一直重试、重试、再重试，直到成功！
#


# 基础镜像，当不存在匹配镜像时，将自动下载。
FROM debian:12.1 AS base
#FROM amd64/debian:12.1 AS base

# 镜像维护者
LABEL maintainer="cockroach888@outlook.com"

# 工作结束时
FROM base AS final


# 切换工作目录
WORKDIR /setup


# 参数定义
ARG FILENAME
RUN echo ${FILENAME}


ARG LIBCBIN="libc-bin_2.36-9+deb12u1_amd64.deb"
ARG LIBBSD0="libbsd0_0.11.7-2_amd64.deb"
ARG LIBC6="libc6_2.36-9+deb12u1_amd64.deb"
ARG LIBCL10N="libc-l10n_2.36-9+deb12u1_all.deb"
ARG LIBCURL4="libcurl4_7.88.1-10+deb12u1_amd64.deb"
ARG LIBMD0="libmd0_1.0.4-2_amd64.deb"
ARG LIBNCURSES6="libncurses6_6.4-4_amd64.deb"
ARG LIBNCURSESW6="libncursesw6_6.4-4_amd64.deb"
ARG LIBPROCPS8="libprocps8_3.3.17-5_amd64.deb"


ARG ARG2HTTPS="apt-transport-https_2.6.1_all.deb"
ARG ARG2CA="ca-certificates_20230311_all.deb"
ARG ARG2SSL="openssl_3.0.9-1_amd64.deb"
ARG ARG2CURL="curl_7.88.1-10+deb12u1_amd64.deb"
ARG ARG2PS="procps_4.0.2-3_amd64.deb"
ARG ARG2OPENBSD="netcat-openbsd_1.219-1_amd64.deb"
ARG ARG2TRADITIONAL="netcat-traditional_1.10-47_amd64.deb"
ARG ARG2NETTOOLS="net-tools_2.10-0.1_amd64.deb"

ARG ARG2TINI="tini_0.19.0-1_amd64.deb"
ARG ARG2LOCALES="locales_2.36-9+deb12u1_all.deb"
ARG ARG2TZDATA="tzdata_2023c-5_all.deb"
ARG ARG2VIM="vim_9.0.1378-2_amd64.deb"

ARG ARG2GDB=gdb_13.1-3_amd64.deb
ARG ARG2LESS=less_590-2_amd64.deb
ARG ARG2TMUX=tmux_3.3a-3_amd64.deb
ARG ARG2VALGRIND=valgrind_3.19.0-1_amd64.deb
ARG ARG2ZLIB1G=zlib1g_1.2.13.dfsg-1_amd64.deb



# 复制安装包到容器目录
COPY ./setup/* /setup/


# 安装 TDEngeing 数据库
RUN dpkg -i ${FILENAME}


# 安装依赖库
RUN dpkg -i ${LIBCBIN}
RUN dpkg -i ${LIBBSD0}
RUN dpkg -i ${LIBC6}
RUN dpkg -i ${LIBCL10N}
RUN dpkg -i ${LIBCURL4}
RUN dpkg -i ${LIBMD0}
RUN dpkg -i ${LIBNCURSES6}
RUN dpkg -i ${LIBNCURSESW6}
RUN dpkg -i ${LIBPROCPS8}


# 安装 HTTPS
RUN dpkg -i ${ARG2HTTPS}

# 安装 CA证书
RUN dpkg -i ${ARG2CA}

# 安装 OpenSSL
RUN dpkg -i ${ARG2SSL}

# 安装 curl
RUN dpkg -i ${ARG2CURL}

# 安装进程查看
RUN dpkg -i ${ARG2PS}

# 安装网络连接工具
RUN dpkg -i ${ARG2OPENBSD}
RUN dpkg -i ${ARG2TRADITIONAL}
RUN dpkg -i ${ARG2NETTOOLS}


# 安装 Tini
RUN dpkg -i ${ARG2TINI}

# 安装国际化
RUN dpkg -i ${ARG2LOCALES}

# 安装时钟同步
RUN dpkg -i ${ARG2TZDATA}

# 安装VIM编辑器
RUN dpkg -i ${ARG2VIM}


# 安装GNU Debugger工具
RUN dpkg -i ${ARG2GDB}

# 安装分页程序
RUN dpkg -i ${ARG2LESS}

# 安装terminal multiplexer工具
RUN dpkg -i ${ARG2TMUX}

# 安装instrumentation framework for building dynamic analysis tools
RUN dpkg -i ${ARG2VALGRIND}

# 安装压缩库
RUN dpkg -i ${ARG2ZLIB1G}


# 更新系统
RUN DEBIAN_FRONTEND=noninteractive apt-get update

# 配置国际化、清理
RUN locale-gen en_US.UTF-8 && apt-get clean && rm -rf /setup/* && rm -rf /var/lib/apt/lists/*


# 设置环境变量
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib" \
    LC_CTYPE=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

# 复制入口点脚本，注意脚本文件的对齐标志，是否为Linux格式。
COPY ./bin/* /usr/bin/

# 为脚本添加权限
RUN chmod +x /tini
RUN chmod +x /usr/bin/entrypoint.sh

# 容器入口点
ENTRYPOINT ["/tini", "--", "/usr/bin/entrypoint.sh"]

# 执行命令
CMD ["taosd"]

# 添加磁盘卷
VOLUME [ "/var/lib/taos", "/var/log/taos", "/corefile" ]
